/* eslint-disable jsx-a11y/no-static-element-interactions */
import { useColorsState } from 'hooks';
import { useEffect, useRef, useState } from 'react';
import { classNames, generateTextColor } from 'utils';
import { ReactComponent as CloseIcon } from 'assets/svg/close.svg';
import { BASE_COLOR } from 'constants';
import { WallpaperToolbar } from './WallpaperToolbar';

export const WallpaperEditor = () => {
  const { selectedColor, wallpaperVisible, closeWallpaper, wallpaperStyle } = useColorsState();
  const [hidden, setHidden] = useState(true);
  const wallpaperRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    const escListener = (e: KeyboardEvent) => {
      if (e.key === 'Escape') {
        closeWallpaper();
      }
    };
    window.addEventListener('keydown', escListener);

    return () => {
      window.removeEventListener('keydown', escListener);
    };
  }, []);

  useEffect(() => {
    if (wallpaperVisible) {
      setHidden(false);
    }
  }, [wallpaperVisible]);

  const handleCloseWallpaper = () => {
    closeWallpaper();
    setTimeout(() => {
      setHidden(true);
    }, 500);
  };

  return (
    <div
      className={classNames(
        'fixed flex top-0 left-0 z-[0] transition-all duration-300 h-full w-full',
        wallpaperVisible ? 'slide-top z-[1000]' : 'slide-bottom',
        hidden ? 'hidden' : ''
      )}
      id="wallpaper-editor"
    >
      <div className="relative h-full w-full z-[2000]">
        <CloseIcon
          className="absolute top-10 right-10 cursor-pointer opacity-30 hover:opacity-100"
          height={32}
          onClick={() => handleCloseWallpaper()}
        />
        <WallpaperToolbar wallpaperRef={wallpaperRef} />
      </div>
      <div
        className={classNames('absolute duration-500 transition h-full w-full wallpaper')}
        style={{ backgroundColor: selectedColor }}
        ref={wallpaperRef}
      >
        {wallpaperStyle === '1' && (
          <div
            className="absolute top-[5%] left-[5%] font-[helvetica] font-semibold"
            style={{ color: generateTextColor(selectedColor) }}
          >
            <div className="">
              <p className="text-5xl mb-4">&quot;{BASE_COLOR[selectedColor].name}&quot;</p>
              <p className="text-5xl mb-4 uppercase">SHADES OF {BASE_COLOR[selectedColor].shade}</p>
              {/* <p className="text-5xl mb-4">
                Generated by <span className="text-primary">chromax.io</span>
              </p> */}
            </div>
          </div>
        )}
        {wallpaperStyle === '1' && (
          <div
            className="absolute druation-300 bottom-[5%] right-[5%] font-[helvetica] font-semibold w-full"
            style={{ color: generateTextColor(selectedColor) }}
          >
            <div className="grid grid-cols-2 text-right">
              <p className="text-4xl mb-4">Article: </p>
              <p className="text-4xl mb-4 uppercase">{BASE_COLOR[selectedColor].article}</p>
              <p className="text-4xl mb-4">HEX:</p>
              <p className="text-4xl mb-4 uppercase">{selectedColor}</p>
              <p className="text-4xl mb-4">Spotted in:</p>
              <p className="text-4xl mb-4 uppercase">{BASE_COLOR[selectedColor].location}</p>
              <p className="text-4xl mb-4">Type:</p>
              <p className="text-4xl mb-4 first-letter:uppercase uppercase">
                {BASE_COLOR[selectedColor].type}
              </p>
            </div>
          </div>
        )}
      </div>
    </div>
  );
};
