/* eslint-disable jsx-a11y/no-static-element-interactions */
import { useColorsState, useInfoPopup } from 'hooks';
import { useEffect, useRef, useState } from 'react';
import { classNames, generateTextColor } from 'utils';
import { ReactComponent as CloseIcon } from 'assets/svg/close.svg';
import { BASE_COLOR } from 'constants';
import { WallpaperToolbar } from './WallpaperToolbar';
import { HelpOverlay } from 'components';

export const WallpaperEditor = () => {
  const {
    selectedColor,
    wallpaperVisible,
    closeWallpaper,
    wallpaperStyle,
    shouldShowHelp,
    closeHelp,
  } = useColorsState();
  const [hidden, setHidden] = useState(true);

  // contact email
  const { showPopup } = useInfoPopup();
  const CONTACT_EMAIL = 'darren@chromax.io';

  // refs
  const wallpaperRef = useRef<HTMLDivElement>(null);
  const stylesToolbarRef = useRef<HTMLDivElement>(null);
  const toolbarRef = useRef<HTMLDivElement>(null);
  const downloadButtonRef = useRef<HTMLDivElement>(null);
  const helpButtonRef = useRef<HTMLDivElement>(null);

  // help
  const HELP_STEPS = [
    {
      targetRef: toolbarRef,
      text: (
        <p className="text-lg mb-4">
          The toolbar designed for the wallpaper editor is presented here.
        </p>
      ),
    },
    {
      targetRef: stylesToolbarRef,
      text: (
        <p className="text-lg mb-4">
          We have 3 different styles to choose from in this section. Additional styling and
          personalization options are coming soon!
        </p>
      ),
      width: 450,
    },
    {
      targetRef: downloadButtonRef,
      text: (
        <p className="text-lg mb-4">
          After you have finished creating your wallpaper, press the download button to save it!
        </p>
      ),
      width: 450,
    },
    {
      targetRef: helpButtonRef,
      text: (
        <p className="text-lg mb-4">
          That concludes the instructions! You can access this help guide again by clicking on the
          help button.
        </p>
      ),
      width: 450,
    },
    {
      targetRef: helpButtonRef,
      text: (
        <p className="text-lg mb-4">
          If you have any feedback or ideas, please do not hesitate to reach out to me via{' '}
          <span
            className="text-blue-600 underline cursor-pointer"
            onClick={() => {
              navigator.clipboard.writeText(CONTACT_EMAIL);
              showPopup('Copied to clipboard!');
            }}
          >
            {CONTACT_EMAIL}
          </span>
          . Thank you :)
        </p>
      ),
      width: 450,
    },
  ];

  useEffect(() => {
    const escListener = (e: KeyboardEvent) => {
      if (e.key === 'Escape') {
        closeWallpaper();
        closeHelp();
      }
    };
    window.addEventListener('keydown', escListener);

    return () => {
      window.removeEventListener('keydown', escListener);
    };
  }, []);

  useEffect(() => {
    if (wallpaperVisible) {
      setHidden(false);
    }
  }, [wallpaperVisible]);

  const handleCloseWallpaper = () => {
    closeWallpaper();
    setTimeout(() => {
      setHidden(true);
    }, 500);
    closeHelp();
  };

  return (
    <div
      className={classNames(
        'fixed flex top-0 left-0 z-[0] transition-all duration-300 h-full w-full',
        wallpaperVisible ? 'slide-top z-[999]' : 'slide-bottom',
        hidden ? 'hidden' : ''
      )}
      id="wallpaper-editor"
    >
      <div className="relative h-full w-full">
        <CloseIcon
          className="absolute top-10 right-10 cursor-pointer opacity-70 hover:opacity-100 z-[1000]"
          height={32}
          onClick={() => handleCloseWallpaper()}
          color={generateTextColor(selectedColor)}
        />
        <WallpaperToolbar
          wallpaperRef={wallpaperRef}
          stylesToolbarRef={stylesToolbarRef}
          toolbarRef={toolbarRef}
          downloadButtonRef={downloadButtonRef}
          helpButtonRef={helpButtonRef}
        />
      </div>
      <div
        className={classNames('absolute duration-500 transition h-full w-full wallpaper')}
        style={{ backgroundColor: selectedColor }}
        ref={wallpaperRef}
      >
        {wallpaperStyle === '1' && (
          <div
            className="absolute top-[5%] left-[5%] font-[helvetica] font-semibold"
            style={{ color: generateTextColor(selectedColor) }}
          >
            <div className="">
              <p className="text-5xl mb-4">&quot;{BASE_COLOR[selectedColor].name}&quot;</p>
              <p className="text-5xl mb-4 uppercase">SHADES OF {BASE_COLOR[selectedColor].shade}</p>
              {/* <p className="text-5xl mb-4">
                Generated by <span className="text-primary">chromax.io</span>
              </p> */}
            </div>
          </div>
        )}
        {wallpaperStyle === '2' && (
          <div
            className="absolute top-1/2 left-1/2 -translate-y-1/2 -translate-x-1/2 font-[helvetica] font-semibold"
            style={{ color: generateTextColor(selectedColor) }}
          >
            <div className="">
              <p className="text-5xl mb-4 text-center">
                &quot;{BASE_COLOR[selectedColor].name}&quot;
              </p>
              <p className="text-5xl mb-4 uppercase text-center">
                SHADES OF {BASE_COLOR[selectedColor].shade}
              </p>
              <p className="text-5xl mb-4 uppercase text-center">{selectedColor}</p>
              {/* <p className="text-5xl mb-4">
                Generated by <span className="text-primary">chromax.io</span>
              </p> */}
            </div>
          </div>
        )}
        {wallpaperStyle === '1' && (
          <div
            className="absolute druation-300 bottom-[5%] right-[5%] font-[helvetica] font-semibold w-full"
            style={{ color: generateTextColor(selectedColor) }}
          >
            <div className="grid grid-cols-2 text-right">
              <p className="text-4xl mb-4">Article: </p>
              <p className="text-4xl mb-4 uppercase">{BASE_COLOR[selectedColor].article}</p>
              <p className="text-4xl mb-4">HEX:</p>
              <p className="text-4xl mb-4 uppercase">{selectedColor}</p>
              <p className="text-4xl mb-4">Spotted in:</p>
              <p className="text-4xl mb-4 uppercase">{BASE_COLOR[selectedColor].location}</p>
              <p className="text-4xl mb-4">Type:</p>
              <p className="text-4xl mb-4 first-letter:uppercase uppercase">
                {BASE_COLOR[selectedColor].type}
              </p>
            </div>
          </div>
        )}
        {shouldShowHelp && <HelpOverlay steps={HELP_STEPS} onClose={closeHelp} />}
      </div>
    </div>
  );
};
