// colors and its names
export const BASE_COLOR: {
  [key: string]: { name: string; article: string; location: string; type: string; shade: string };
} = {
  '#FE4743': {
    name: 'Coral Red',
    article: 'Scarlet ibis',
    location: 'South America',
    type: 'animal',
    shade: 'red',
  },
  '#ED1C24': {
    name: 'Crimson',
    article: 'Hong Kong Iconic Taxi',
    location: 'Hong Kong',
    type: 'object',
    shade: 'red',
  },
  '#D31A81': {
    name: 'Cabaret Pink',
    article: 'Moulin Rouge',
    location: 'France',
    type: 'landmark',
    shade: 'red',
  },
  '#C41900': {
    name: 'Fire Engine Red',
    article: 'Strawberry poison dart frog',
    location: 'Central America',
    type: 'animal',
    shade: 'red',
  },
  '#D83300': {
    name: 'Tomato Red',
    article: 'Ladybug',
    location: 'Earth',
    type: 'animal',
    shade: 'red',
  },
  '#CB4154': {
    name: 'Brick Red',
    article: 'Red Square',
    location: 'Russia',
    type: 'landmark',
    shade: 'red',
  },
  '#AA0114': {
    name: 'Mughal Red',
    article: 'Red Fort',
    location: 'India',
    type: 'landmark',
    shade: 'red',
  },
  '#E97451': {
    name: 'Canyon Clay',
    article: 'Valley of Fire State Park',
    location: 'United States',
    type: 'nature',
    shade: 'red',
  },
  '#FF7F50': {
    name: 'Coral',
    article: '-',
    location: '-',
    type: '-',
    shade: 'red',
  },
  '#B5672B': {
    name: 'Mahogany Red',
    article: 'Red panda',
    location: 'Southwestern China',
    type: 'animal',
    shade: 'red',
  },
  '#B22222': {
    name: 'Firebrick',
    article: "Fisherman's Huts",
    location: 'Norway',
    type: 'landmark',
    shade: 'red',
  },
  '#A04534': {
    name: 'Terracotta Red',
    article: 'Zhangye National Geopark',
    location: 'China',
    type: 'nature',
    shade: 'red',
  },
  '#8B3103': {
    name: 'Rust',
    article: 'Lake Natron',
    location: 'Tanzania',
    type: 'nature',
    shade: 'red',
  },
  '#CD5C5C': {
    name: 'Indian Red',
    article: '-',
    location: '-',
    type: '-',
    shade: 'red',
  },
  '#e53d2f': {
    name: 'Vermillion Red',
    article: 'Fushimi Inari',
    location: 'Kyoto, Japan',
    type: 'landmark',
    shade: 'red',
  },
  '#B30000': {
    name: 'Chicago Red',
    article: 'Air Jordan 1 Chicago',
    location: 'Earth',
    type: 'other',
    shade: 'red',
  },
  '#BB2649': {
    name: 'Viva Magenta',
    article: '-',
    location: '-',
    type: '-',
    shade: 'red',
  },
  '#C74375': {
    name: 'Fuchsia Rose',
    article: '-',
    location: '-',
    type: '-',
    shade: 'red',
  },
  '#BF1932': {
    name: 'True Red',
    article: '-',
    location: '-',
    type: '-',
    shade: 'red',
  },
  '#9B1B30': {
    name: 'Chili Pepper',
    article: '-',
    location: '-',
    type: '-',
    shade: 'red',
  },
  '#00CED1': {
    name: 'Turqoise Blue',
    article: 'The Blue Eye',
    location: 'Albania',
    type: 'nature',
    shade: 'blue',
  },
  '#0071C5': {
    name: 'Royal Blue',
    article: 'Jodhpur',
    location: 'India',
    type: 'landmark',
    shade: 'blue',
  },
  '#1A40DB': {
    name: 'Ultramarine Blue',
    article: 'Blue surgeonfish (Dory fish)',
    location: 'Indo-Pacific region',
    type: 'animal',
    shade: 'blue',
  },
  '#3E5994': {
    name: 'Sapphire Blue',
    article: 'Blue coral snake',
    location: 'Indonesia',
    type: 'animal',
    shade: 'blue',
  },
  '#487CB8': {
    name: 'Cornflower Blue',
    article: 'Blue Jay',
    location: 'North America',
    type: 'animal',
    shade: 'blue',
  },
  '#82A8F8': {
    name: 'Periwinkle Blue',
    article: 'Ethereum',
    location: 'INTERNET',
    type: 'cryptocurrency',
    shade: 'blue',
  },
  '#869BB1': {
    name: 'Steel Blue',
    article: 'Little blue heron',
    location: 'America',
    type: 'animal',
    shade: 'blue',
  },
  '#87CEEB': {
    name: 'Sky Blue',
    article: 'Marble Cathedral',
    location: 'Chile',
    type: 'nature',
    shade: 'blue',
  },
  '#B0E0E6': {
    name: 'Ice Blue',
    article: 'Blue Lagoon',
    location: 'Iceland',
    type: 'nature',
    shade: 'blue',
  },
  '#B8E4E1': {
    name: 'Robin Egg Blue',
    article: 'Blue Iguana',
    location: 'Grand Cayman Island',
    type: 'animal',
    shade: 'blue',
  },
  '#0047AB': {
    name: 'Cobalt Blue',
    article: 'Blue Dragon (Glaucus Atlanticus)',
    location: 'Pacific Ocean',
    type: 'animal',
    shade: 'blue',
  },
  '#7DF9FF': {
    name: 'Electric Blue',
    article: 'Blue Grottto',
    location: 'Croatia',
    type: 'nature',
    shade: 'blue',
  },
  '#0F4C81': {
    name: 'Classic Blue',
    article: '-',
    location: '-',
    type: '-',
    shade: 'blue',
  },
  '#7BC4C4': {
    name: 'Aqua Sky',
    article: '-',
    location: '-',
    type: '-',
    shade: 'blue',
  },
  '#9BB7D4': {
    name: 'Cerulean Blue',
    article: '-',
    location: '-',
    type: '-',
    shade: 'blue',
  },
  '#53B0AE': {
    name: 'Blue Turquoise',
    article: '-',
    location: '-',
    type: '-',
    shade: 'blue',
  },
  '#5A5B9F': {
    name: 'Blue Iris',
    article: '-',
    location: '-',
    type: '-',
    shade: 'blue',
  },
  '#92A8D1': {
    name: 'Serenity',
    article: '-',
    location: '-',
    type: '-',
    shade: 'blue',
  },
  '#BDCD02': {
    name: 'Olive Green',
    article: 'Machu Picchu',
    location: 'Peru',
    type: 'landmark',
    shade: 'green',
  },
  '#00C99C': {
    name: 'Caribbean Green',
    article: 'Raja Ampat',
    location: 'Indonesia',
    type: 'nature',
    shade: 'green',
  },
  '#02AA5A': {
    name: 'Jade Green',
    article: 'Northern Lights',
    location: 'Iceland',
    type: 'nature',
    shade: 'green',
  },
  '#18BF31': {
    name: 'Lime Green',
    article: "Chicago River - St. Patrick's Day",
    location: 'Chicago',
    type: 'landmark',
    shade: 'green',
  },
  '#60C098': {
    name: 'Seafoam Green',
    article: 'Statue of Liberty',
    location: 'New York',
    type: 'landmark',
    shade: 'green',
  },
  '#8EB307': {
    name: 'Army Green',
    article: 'Amazon parrots',
    location: 'South America',
    type: 'animal',
    shade: 'green',
  },
  '#CBDF07': {
    name: 'Lemon Lime',
    article: 'Wellington green gecko',
    location: 'New Zealand',
    type: 'animal',
    shade: 'green',
  },
  '#2A9863': {
    name: 'Teal Green',
    article: 'Green peacock',
    location: 'Southeast Asia',
    type: 'animal',
    shade: 'green',
  },
  '#1FC001': {
    name: 'Emerald Green',
    article: 'Emerald tree boa',
    location: 'South America',
    type: 'animal',
    shade: 'green',
  },
  '#2E8B57': {
    name: 'Sea Green',
    article: '-',
    location: '-',
    type: '-',
    shade: 'green',
  },
  '#6B8E23': {
    name: 'Olive Drab',
    article: '-',
    location: '-',
    type: '-',
    shade: 'green',
  },
  '#228B22': {
    name: 'Forest Green',
    article: '-',
    location: '-',
    type: '-',
    shade: 'green',
  },
  '#009473': {
    name: 'Emerald',
    article: '-',
    location: '-',
    type: '-',
    shade: 'green',
  },
  '#88B04B': {
    name: 'Greenery',
    article: '-',
    location: '-',
    type: '-',
    shade: 'green',
  },
  '#F9CE48': {
    name: 'Electric Yellow',
    article: 'Pikachu',
    location: 'UNKNOWN',
    type: 'animal (...kinda)',
    shade: 'yellow',
  },
  '#F5D96A': {
    name: 'Banana yellow',
    article: 'Banana',
    location: 'Supermarket',
    type: 'plant',
    shade: 'yellow',
  },
  '#FFB907': {
    name: 'Tangerine Dream',
    article: 'Skazka Canyon',
    location: 'Kyrgyzstan',
    type: 'nature',
    shade: 'yellow',
  },
  '#FFC512': {
    name: 'Golden Yellow',
    article: 'Sunflower',
    location: 'Earth',
    type: 'plant',
    shade: 'yellow',
  },
  '#FFD700': {
    name: 'Gold',
    article: 'Gold',
    location: 'Earth and beyond',
    type: 'gemstone',
    shade: 'yellow',
  },
  '#FFC87C': {
    name: 'Topaz',
    article: 'Topaz',
    location: 'Earth',
    type: 'gemstone',
    shade: 'yellow',
  },
  '#F0E68C': {
    name: 'Khaki',
    article: '-',
    location: '-',
    type: '-',
    shade: 'yellow',
  },
  '#FFFACD': {
    name: 'Lemon Chiffon',
    article: '-',
    location: '-',
    type: '-',
    shade: 'yellow',
  },
  '#EFCD6A': {
    name: 'Mimosa',
    article: '-',
    location: '-',
    type: '-',
    shade: 'yellow',
  },
  '#F5DF4D': {
    name: 'Illuminating',
    article: '-',
    location: '-',
    type: '-',
    shade: 'yellow',
  },
  '#F08E18': {
    name: 'Dark Orange',
    article: 'Bitcoin',
    location: 'INTERNET',
    type: 'cryptocurrency',
    shade: 'orange',
  },
  '#EE712D': {
    name: 'Flame Orange',
    article: 'channel ORANGE',
    location: 'Frank Ocean',
    type: 'other',
    shade: 'orange',
  },
  '#CB7935': {
    name: 'Amber Haze',
    article: 'Sumatran tiger',
    location: 'Indonesia',
    type: 'animal',
    shade: 'orange',
  },
  '#EF8451': {
    name: 'Salmon Orange',
    article: 'Salmon (the meat)',
    location: 'Supermarket',
    type: 'food',
    shade: 'orange',
  },
  '#DB851A': {
    name: 'Navel Orange',
    article: 'Orange',
    location: 'everywhere',
    type: 'food',
    shade: 'orange',
  },
  '#FF8243': {
    name: 'Pumpkin Blaze',
    article: 'Clownfish',
    location: 'Pacific Ocean',
    type: 'animal',
    shade: 'orange',
  },
  '#D2691E': {
    name: 'Autumn Blaze',
    article: 'Orangutan',
    location: 'Indonesia',
    type: 'animal',
    shade: 'orange',
  },
  '#FFE4B5': {
    name: 'Moccasin',
    article: '-',
    location: '-',
    type: '-',
    shade: 'orange',
  },
  '#CD853F': {
    name: 'Peru',
    article: '-',
    location: '-',
    type: '-',
    shade: 'orange',
  },
  '#E2583E': {
    name: 'Tigerlily',
    article: '-',
    location: '-',
    type: '-',
    shade: 'orange',
  },
  '#E2492F': {
    name: 'Tangerine Tango',
    article: '-',
    location: '-',
    type: '-',
    shade: 'orange',
  },
  '#FF6F61': {
    name: 'Living Coral',
    article: '-',
    location: '-',
    type: '-',
    shade: 'orange',
  },
  '#4B0082': {
    name: 'Indigo',
    article: '-',
    location: '-',
    type: '-',
    shade: 'purple',
  },
  '#9370DB': {
    name: 'Medium Purple',
    article: '-',
    location: '-',
    type: '-',
    shade: 'purple',
  },
  '#DA70D6': {
    name: 'Orchid',
    article: '-',
    location: '-',
    type: '-',
    shade: 'purple',
  },
  '#BA55D3': {
    name: 'Medium Orchid',
    article: '-',
    location: '-',
    type: '-',
    shade: 'purple',
  },
  '#DDA0DD': {
    name: 'Plum',
    article: '-',
    location: '-',
    type: '-',
    shade: 'purple',
  },
  '#932E86': {
    name: 'Amethyst Glow',
    article: 'Lavender Fields',
    location: 'Provence, France',
    type: 'nature',
    shade: 'purple',
  },
  '#CC8899': {
    name: 'Purple',
    article: '-',
    location: '-',
    type: '-',
    shade: 'purple',
  },
  '#D941CF': {
    name: 'Orchid Bloom',
    article: 'Takinoue Park',
    location: 'Japan',
    type: 'nature',
    shade: 'purple',
  },
  '#61057B': {
    name: 'Grape Royale',
    article: 'Grape',
    location: 'everywhere',
    type: 'food',
    shade: 'purple',
  },
  '#6A0DAD': {
    name: 'Plum Perfection',
    article: 'Eggplant',
    location: 'everywhere',
    type: 'food',
    shade: 'purple',
  },
  '#5F4B8B': {
    name: 'Ultra Violet',
    article: '-',
    location: '-',
    type: '-',
    shade: 'purple',
  },
  '#6667AB': {
    name: 'Very Peri',
    article: '-',
    location: '-',
    type: '-',
    shade: 'purple',
  },
  '#FF1493': {
    name: 'Deep Pink',
    article: '-',
    location: '-',
    type: '-',
    shade: 'pink',
  },
  '#FF69B4': {
    name: 'Hot Pink',
    article: '-',
    location: '-',
    type: '-',
    shade: 'pink',
  },
  '#DB7093': {
    name: 'Pale Violet Red',
    article: '-',
    location: '-',
    type: '-',
    shade: 'pink',
  },
  '#FFC0CB': {
    name: 'Pink',
    article: 'Flamingo',
    location: 'Earth',
    type: 'animal',
    shade: 'pink',
  },
  '#FFB6C1': {
    name: 'Light Pink',
    article: '-',
    location: '-',
    type: '-',
    shade: 'pink',
  },
  '#D09098': {
    name: 'Blush Rose',
    article: 'Royal Hawaiian Hotel',
    location: 'Honolulu, Hawaii',
    type: 'landmark',
    shade: 'pink',
  },
  '#E9A2A9': {
    name: 'Pink Peony',
    article: 'Muralla Roja',
    location: 'Calp, Spain',
    type: 'landmark',
    shade: 'pink',
  },
  '#F4D0E1': {
    name: 'Cotton Candy',
    article: 'Tangsi Beach',
    location: 'Lombok, Indonesia',
    type: 'nature',
    shade: 'pink',
  },
  '#F5B5C5': {
    name: 'Sakura Pink',
    article: 'Cherry Blossoms',
    location: 'Japan',
    type: 'nature',
    shade: 'pink',
  },
  '#E076B7': {
    name: 'Rosy Radiance',
    article: 'Paul Smith store',
    location: 'Los Angeles',
    type: 'landmark',
    shade: 'pink',
  },
  '#D94F70': {
    name: 'Fuchsia',
    article: '-',
    location: '-',
    type: '-',
    shade: 'pink',
  },
  '#F7CAC9': {
    name: 'Rose Quartz',
    article: '-',
    location: '-',
    type: '-',
    shade: 'pink',
  },
  '#8B4513': {
    name: 'Saddle Brown',
    article: 'Shiba Inu',
    location: 'Earth',
    type: 'animal',
    shade: 'brown',
  },
  '#DEB887': {
    name: 'Burlywood',
    article: '-',
    location: '-',
    type: '-',
    shade: 'brown',
  },
  '#BC8F8F': {
    name: 'Rosy Brown',
    article: '-',
    location: '-',
    type: '-',
    shade: 'brown',
  },
  '#4B3832': {
    name: 'Coffee Bean',
    article: 'Coffee Bean',
    location: 'Earth',
    type: 'other',
    shade: 'brown',
  },
  '#C19A6B': {
    name: 'Desert Sand',
    article: 'Pyramids of Giza',
    location: 'Egypt',
    type: 'landmark',
    shade: 'brown',
  },
  '#DECDBE': {
    name: 'Sand Dollar',
    article: '-',
    location: '-',
    type: '-',
    shade: 'brown',
  },
  '#955251': {
    name: 'Marsala',
    article: '-',
    location: '-',
    type: '-',
    shade: 'brown',
  },
  '#A0522D': {
    name: 'Sienna',
    article: '-',
    location: '-',
    type: '-',
    shade: 'brown',
  },
  '#F4A460': {
    name: 'Sandy Brown',
    article: '-',
    location: '-',
    type: '-',
    shade: 'brown',
  },
  '#696969': {
    name: 'Dim Gray',
    article: '-',
    location: '-',
    type: '-',
    shade: 'gray',
  },
  '#808080': {
    name: 'Gray',
    article: '-',
    location: '-',
    type: '-',
    shade: 'gray',
  },
  '#A9A9A9': {
    name: 'Dark Gray',
    article: '-',
    location: '-',
    type: '-',
    shade: 'gray',
  },
  '#C0C0C0': {
    name: 'Silver',
    article: '-',
    location: '-',
    type: '-',
    shade: 'gray',
  },
  '#D3D3D3': {
    name: 'Light Gray',
    article: '-',
    location: '-',
    type: '-',
    shade: 'gray',
  },
  '#939597': {
    name: 'Ultimate Gray',
    article: '-',
    location: '-',
    type: '-',
    shade: 'gray',
  },
  '#f5f5dc': {
    name: 'Off White',
    article: '-',
    location: '-',
    type: '-',
    shade: 'white',
  },
  '#FFFFF0': {
    name: 'Ivory',
    article: '-',
    location: '-',
    type: '-',
    shade: 'white',
  },
  '#FFFAF0': {
    name: 'Floral White',
    article: '-',
    location: '-',
    type: '-',
    shade: 'white',
  },
  '#F5F5F5': {
    name: 'White Smoke',
    article: '-',
    location: '-',
    type: '-',
    shade: 'white',
  },
  '#FFF5EE': {
    name: 'Seashell',
    article: '-',
    location: '-',
    type: '-',
    shade: 'white',
  },
  '#FFFFFF': {
    name: 'True White',
    article: '-',
    location: '-',
    type: '-',
    shade: 'white',
  },
  '#F8F8FF': {
    name: 'Ghost White',
    article: '-',
    location: '-',
    type: '-',
    shade: 'white',
  },
  '#000000': {
    name: 'True Black',
    article: 'Darkness my old friend',
    location: 'everywhere',
    type: 'other',
    shade: 'black',
  },
  '#1D2021': {
    name: 'Charcoal Black',
    article: 'Charcoal',
    location: 'Earth',
    type: 'nature',
    shade: 'black',
  },
  '#3D3D3D': {
    name: 'Jet Black',
    article: 'iPhone 7',
    location: 'everywhere',
    type: 'other',
    shade: 'black',
  },
};

// colors and its hex values
// export const reds = [
//   '#e53d2f',
//   '#ED1C24',
//   '#8B3103',
//   '#AA0114',
//   '#E97451',
//   '#A04534',
//   '#B22222',
//   '#C41900',
//   '#B5672B',
//   '#D83300',
//   '#FE4743',
// ];
// export const blues = [
//   '#0071C5',
//   '#00CED1',
//   '#B0E0E6',
//   '#4F94CD',
//   '#0047AB',
//   '#7DF9FF',
//   '#487CB8',
//   '#B8E4E1',
//   '#3E5994',
//   '#869BB1',
//   '#1A40DB',
// ];
// export const greens = ['#228B22', '#32CD32', '#6B8E23', '#2E8B57', '#66CDAA'];
// export const yellows = ['#FFD700', '#F0E68C', '#FFFFE0', '#FFFACD', '#FFE4B5'];
// export const oranges = ['#FF8C00', '#FF7F50', '#F4A460', '#CD853F'];
// export const purples = ['#4B0082', '#9370DB', '#DA70D6', '#BA55D3', '#DDA0DD'];
// export const pinks = ['#D31A81', '#FF69B4', '#DB7093', '#FFC0CB', '#FFB6C1'];
// export const browns = ['#8B4513', '#A0522D', '#DEB887', '#BC8F8F'];
// export const blacks = ['#696969', '#808080', '#A9A9A9', '#C0C0C0', '#D3D3D3'];
// export const whites = ['#FFFFF0', '#FFFAF0', '#F8F8FF', '#F5F5F5', '#FFF5EE'];
// export const all_colors: string[] = reds.concat(
//   blues,
//   greens,
//   yellows,
//   oranges,
//   purples,
//   pinks,
//   browns,
//   blacks,
//   whites,
// );

// colors and explanation
export const COLOR_BRAND_EXPLANATION: { [key: string]: string } = {
  red: 'Red is a bold and powerful color that represents energy, passion, and excitement. It is often used by brands that want to convey a sense of urgency or stimulate an emotional response. Red can be associated with love, anger, and danger, making it a popular choice for brands in the food, sports, and automotive industries.',
  blue: 'Blue is a calming and stable color that symbolizes trust, reliability, and loyalty. It is often used by brands to evoke feelings of security and professionalism. Blue is a popular choice for corporate and technology brands, as well as those in the financial and healthcare sectors, as it conveys competence and credibility.',
  green:
    'Green is a versatile color that represents growth, nature, and harmony. It is often used by brands that want to convey an eco-friendly or healthy image. Green can be associated with freshness, renewal, and balance, making it a popular choice for brands in the food, wellness, and sustainability industries.',
  yellow:
    'Yellow is a bright and cheerful color that symbolizes optimism, warmth, and happiness. It is often used by brands that want to convey a sense of friendliness and approachability. Yellow can be associated with creativity, energy, and positivity, making it a popular choice for brands in the entertainment, food, and retail industries.',
  orange:
    'Orange is an energetic and vibrant color that represents enthusiasm, creativity, and adventure. It is often used by brands that want to convey a sense of fun and excitement. Orange can be associated with warmth, optimism, and motivation, making it a popular choice for brands in the travel, sports, and technology industries.',
  purple:
    'Purple is a luxurious and sophisticated color that symbolizes royalty, wisdom, and creativity. It is often used by brands that want to convey a sense of luxury and exclusivity. Purple can be associated with mystery, spirituality, and elegance, making it a popular choice for brands in the fashion, beauty, and wellness industries.',
  pink: 'Pink is a soft and romantic color that represents love, compassion, and femininity. It is often used by brands that want to convey a sense of warmth, nurturing, and playfulness. Pink can be associated with sweetness, innocence, and sensuality, making it a popular choice for brands in the fashion, beauty, and confectionery industries.',
  brown:
    'Brown is a warm and earthy color that represents stability, reliability, and groundedness. It is often used by brands that want to convey a sense of durability and dependability. Brown can be associated with nature, comfort, and tradition, making it a popular choice for brands in the food, furniture, and outdoor industries.',
  black:
    'Black is a strong and sophisticated color that represents elegance, power, and authority. It is often used by brands that want to convey a sense of luxury and exclusivity. Black can be associated with formality, mystery, and seriousness, making it a popular choice for brands in the fashion, automotive, and technology industries.',
  white:
    'White is a clean and simple color that represents purity, innocence, and minimalism. It is often used by brands that want to convey a sense of simplicity and sophistication. White can be associated with freshness, clarity, and modernity, making it a popular choice for brands in the technology, healthcare, and home goods industries.',
};
